
// File-based app to generate the JsonSerializerContext
// Generates the DefaultJsonSerializerContext.cs from all classes in the Models folder 

#:package Microsoft.CodeAnalysis.CSharp@4.14.0

using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

string modelsDirectoryPath = @"../../src/Docker.DotNet/Models";
var modelFiles = Directory.GetFiles(modelsDirectoryPath, "*.cs", SearchOption.AllDirectories);

string endpointDirectoryPath = @"../../src/Docker.DotNet/Endpoints";
var endpointFiles = Directory.GetFiles(endpointDirectoryPath, "*.cs", SearchOption.AllDirectories);

HashSet<string> allBaseTypeDeclarations = [];
HashSet<string> allDynamicDependenciesAttributes = [];
HashSet<string> allPropertyDeclarations = [];
HashSet<string> allDockerApiResponseTypes = [];

foreach (var file in modelFiles)
{
    var code = File.ReadAllText(file);
    var tree = CSharpSyntaxTree.ParseText(code);
    var root = tree.GetCompilationUnitRoot();

    var baseTypeDeclarations = root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>();

    foreach (var typeDecl in baseTypeDeclarations)
    {
        var name = typeDecl.Identifier.Text;
        allBaseTypeDeclarations.Add($"[JsonSerializable(typeof({name}))]");
        allDynamicDependenciesAttributes.Add($"[DynamicDependency(DynamicallyAccessedMemberTypes.PublicProperties, typeof(Docker.DotNet.Models.{name}))]");
    }

    var propertyDeclarations = root.DescendantNodes().OfType<PropertyDeclarationSyntax>();

    foreach (var typeSyntax in propertyDeclarations)
    {
        var typeString = typeSyntax.Type.ToString();
        if (typeString.StartsWith("IDictionary") || typeString.StartsWith("IList"))
        {
            allPropertyDeclarations.Add($"[JsonSerializable(typeof({typeString}))]");
            allPropertyDeclarations.Add($"[JsonSerializable(typeof({typeString.Substring(1)}))]");
        }
    }
}

foreach (var file in endpointFiles)
{
    var code = File.ReadAllText(file);
    var tree = CSharpSyntaxTree.ParseText(code);
    var root = tree.GetCompilationUnitRoot();

    var invocations = root.DescendantNodes().OfType<InvocationExpressionSyntax>();

    foreach (var invocation in invocations)
    {
        if (invocation.Expression is MemberAccessExpressionSyntax memberAccess
            && memberAccess.Name is GenericNameSyntax genericMember
            && genericMember.Identifier.Text.Contains("MakeRequestAsync"))
        {
            foreach (var typeArg in genericMember.TypeArgumentList.Arguments)
            {
                allDockerApiResponseTypes.Add($"[JsonSerializable(typeof({typeArg.ToString()}))]");
            }
        }
    }
}

var fileContent =
$$"""
// <autogenerated />

using Docker.DotNet.Models;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;

using Version = Docker.DotNet.Models.Version;

namespace Docker.DotNet;

{{string.Join(Environment.NewLine, allBaseTypeDeclarations)}}

{{string.Join(Environment.NewLine, allPropertyDeclarations)}}

{{string.Join(Environment.NewLine, allDockerApiResponseTypes)}}

[JsonSourceGenerationOptions(
    UseStringEnumConverter = true,
    Converters =
    [
        typeof(JsonEnumMemberConverter<TaskState>),
        typeof(JsonEnumMemberConverter<RestartPolicyKind>),
        typeof(JsonDateTimeConverter),
        typeof(JsonNullableDateTimeConverter),
        typeof(JsonBase64Converter)
    ])]
public partial class DockerDotnetJsonSerializerContext : JsonSerializerContext
{
    {{string.Join(Environment.NewLine + "    ", allDynamicDependenciesAttributes)}}
    internal static void PreserveReflection()
    {
    }
}

""";


string savePath = @"../../src/Docker.DotNet/DockerDotnetJsonSerializerContext.Generated.cs";
File.WriteAllText(savePath, fileContent);
